### ISSUE TITLE
v3.01 Script fails to set permission when dataset is configured with acls

### ISSUE THREAD

**Issue by jafin** [JoeSchmuck/Multi-Report#2]
Platform: `TrueNAS-SCALE-22.12.4.2`

## Issue
When the upgrade script runs on a dataset that is configured with nfsacls the `chmod` command errors with

`chmod: changing permissions of 'multi_report.sh': Operation not permitted`

## Expected
If there is some way to detect before hand if the dataset is configured with acls to avoid running (and erroring) when running the `chmod` command.

## Code
https://github.com/JoeSchmuck/Multi-Report/blob/927f9ad4add2aa5f620d6fd8db932da87fb1b3a3/multi_report_v3.0.1_2024_04_13.txt#L804C4-L804C40

**Comment by JoeSchmuck** [comment]
Unfortunately, I’m not an ACL expert and I dislike them myself.  If the script runs after the upgrade then you can ignore the chmod error, it is only there to change the script into an executable if it needs it.  If you have a suggestion on how to fix it, I’m all ears.

-Joe

From: Jason Finch ***@***.***>
Sent: Wednesday, April 17, 2024 5:44 PM
To: JoeSchmuck/Multi-Report ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JoeSchmuck/Multi-Report] v3.01 Script fails to set permission when dataset is configured with acls (Issue #2)


Platform: TrueNAS-SCALE-22.12.4.2

Issue

When the upgrade script runs on a dataset that is configured with nfsacls the chmod command errors with

chmod: changing permissions of 'multi_report.sh': Operation not permitted

Expected

If there is some way to detect before hand if the dataset is configured with acls to avoid running (and erroring) when running the chmod command.

Code

https://github.com/JoeSchmuck/Multi-Report/blob/927f9ad4add2aa5f620d6fd8db932da87fb1b3a3/multi_report_v3.0.1_2024_04_13.txt#L804C4-L804C40
